---
engines:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
exclude_paths:
- "test/"
- "patterns/"
- "**/vendor/"
- "*.rb"
- "js/*"
- "node-modules/"
- "coverage/"
